### PR TITLE
Fix for gutenberg wordpress editor

### PR DESCRIPTION
**Pull request by forgetso**

### CODE REVIEW

**Comment by bill393** [comment]
Tested [Version 1.7.3]. It still doesn't work. 🙁 @forgetso

**Comment by forgetso** [comment]
Hi @bill393, could you please send me a video of you testing it so that I can replicate what you're doing?

[I have it working](https://imgur.com/a/MAEvfX0) in WordPress 6.3.2 in the default post editor.

**Comment by bill393** [comment]
[https://gemoo.com/tools/upload-video/share/580502654328049664?codeId=v6g0WWWAdr3lo&card=580502650448318464](the test video)

As reported in the Chrome Webstore, it works in the editing state, but only a part of it takes effect on the frontend page after saving. Many areas are not effective, and further search and replace are no longer effective. 

I have tested multiple websites, and they all exhibit the same behavior. This is also the case when testing on a new site without any other plugins.

**Comment by forgetso** [comment]
Thanks for the video. I've figured out what the problem was and 1.7.4 fixes it: https://imgur.com/a/3Um4PEB

It will be released within the next day.

**Comment by bill393** [comment]
> @bill393 1.7.4 is now released. Please let me know if it works for you.

It still doesn't work...

**Comment by bill393** [comment]
You could try using Bing Chat to generate a paragraph with multiple corner characters and then test with that, after all, that's what I did.

In addition, I found that after finishing the text replacement in the edit page, select the paragraph just now that has been replaced, copy it and then paste it into a new paragraph, at this time you will find that this new paragraph is the same as it was before replacing the text. So it won't take effect even after saving.

**Comment by forgetso** [comment]
I've copied some text from Bing chat. It's likely the problem is that it's returning HTML so you can't search directly for 123.

This:

image

Is actually equivalent to this in the HTML of the page:

```html
<a href="https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth" target="_blank" rel="noreferrer noopener"><sup>1</sup></a>
<a href="https://bing.com/search?q=height+of+the+tallest+mountains+in+the+world" target="_blank" rel="noreferrer noopener"><sup>2</sup></a>
<a href="https://www.britannica.com/place/Mount-Everest" target="_blank" rel="noreferrer noopener"><sup>3</sup></a>
```

Pay attention to the sections surrounded by `<sup>`. These are your references

```html
<sup>1</sup>
```
To change these values individually you could search for `<sup>1</sup>`.

To change them all at once, you could search using regular expressions for `<sup>[0-9]+</sup>`, although you would only be able to replace with a single value. This would work if you're simply trying to remove the citations. I've demonstrated [this in a video](https://i.imgur.com/Otb9GSN.mp4).

Hope this helps.

**Comment by bill393** [comment]
I don't think it's a problem with the `<sup>` tag, because it doesn't work when I test replacing regular characters either. It's really strange..

**Comment by forgetso** [comment]
That is very strange. I can't replicate the behaviour but you could always debug locally using the following steps:

1. Clone this repo ```git clone https://github.com/forgetso/search-replace.git```
2. Uninstall Search and Replace
3. [Enable developer mode in Extensions menu of chrome](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked) so that you can load unpacked Chrome extensions
4. Go to the directory where you cloned this repo
5. Install the dependencies `npm i`
6. Build the extension in development mode ```npm run watch``` (this will create a directory called `dist`)
7. Go to the [Extensions page](chrome://extensions) and select `Load Unpacked`
8. Navigate to the root folder of the repository and select the `dist` folder and press ok

You will now have a local copy of the extension running in your browser. You can edit the TypeScript files and the extension will automatically rebuild thanks to the `npm run watch` command. To see the changes in your browser you will need to hit the reload button underneath Search and Replace on the [Extensions page](chrome://extensions) and then also reload the web page on which you are doing the replacements.

My suggestion would be to add some `console.log` statements throughout the code to try and identify what's going wrong. If you solve it and you can fix it, feel free to submit a PR!

**Pull request merged**
